workspace:
  base: /go
  path: src/github.com/falconray0704/drone-test-go

pipeline:
  test:
    image: golang:latest
    commands:
      - go vet
      - go test -v -cover
  build:
    image: golang:latest
    commands:
      - go build

